/** @type {import('next').NextConfig} */
const nextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '*.akamaized.net' },
      { protocol: 'https', hostname: '*.alicdn.com' },
      { protocol: 'https', hostname: '*.apple.com' },
      { protocol: 'https', hostname: '*.bbci.co.uk' },
      { protocol: 'https', hostname: '*.behance.net' },
      { protocol: 'https', hostname: '*.canva.com' },
      { protocol: 'https', hostname: '*.cdninstagram.com' },
      { protocol: 'https', hostname: '*.coinmarketcap.com' },
      { protocol: 'https', hostname: '*.cnn.com' },
      { protocol: 'https', hostname: '*.cnnindonesia.com' },
      { protocol: 'https', hostname: 'deo.shopeemobile.com' },
      { protocol: 'https', hostname: '*.detik.net.id' },
      { protocol: 'https', hostname: '*.dribbble.com' },
      { protocol: 'https', hostname: '*.facebook.com' },
      { protocol: 'https', hostname: '*.fbcdn.net' },
      { protocol: 'https', hostname: '*.fbsbx.com' },
      { protocol: 'https', hostname: '*.github.com' },
      { protocol: 'https', hostname: '*.githubusercontent.com' },
      { protocol: 'https', hostname: '*.githubassets.com' },
      { protocol: 'https', hostname: '*.google.com' },
      { protocol: 'https', hostname: '*.gstatic.com' },
      { protocol: 'https', hostname: '*.instagram.com' },
      { protocol: 'https', hostname: '*.linkedin.com' },
      { protocol: 'https', hostname: '*.pinimg.com' },
      { protocol: 'https', hostname: '*.reddit.com' },
      { protocol: 'https', hostname: '*.redd.it' },
      { protocol: 'https', hostname: '*.redditstatic.com' },
      { protocol: 'https', hostname: '*.tiktok.com' },
      { protocol: 'https', hostname: '*.tiktokcdn.com' },
      { protocol: 'https', hostname: '*.twimg.com' },
      { protocol: 'https', hostname: '*.twitter.com' },
      { protocol: 'https', hostname: '*.yandex.net' },
      { protocol: 'https', hostname: '*.youtube.com' },
      { protocol: 'https', hostname: '*.ytimg.com' },
      { protocol: 'https', hostname: 'api.microlink.io' },
      { protocol: 'https', hostname: 'assets.bibit.id' },
      { protocol: 'https', hostname: 'assets.opengraph.io' },
      { protocol: 'https', hostname: 'cdn.oaistatic.com' },
      { protocol: 'https', hostname: 'cdn.prod.website-files.com' },
      { protocol: 'https', hostname: 'code.visualstudio.com' },
      { protocol: 'https', hostname: 'framerusercontent.com' },
      { protocol: 'https', hostname: 'huggingface.co' },
      { protocol: 'https', hostname: 'images.bareksa.com' },
      { protocol: 'https', hostname: 'opengraph.io' },
      { protocol: 'https', hostname: 'placehold.co' },
      { protocol: 'https', hostname: 'sc.cnbcfm.com' },
      { protocol: 'https', hostname: 'upload.wikimedia.org' },
      { protocol: 'https', hostname: 'www.deepl.com' },
      { protocol: 'https', hostname: 'www.notion.so' },
    ].map(p => ({ ...p, port: '', pathname: '/**' })),
  },
};

module.exports = nextConfig;
